# Pod configuration
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-volume
      mountPath: /usr/nginx/html
  - name: sidecar-container
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the sidecar container; sleep 300"]

# CM configuration
# --- gives the ability to use more than one component in one config file.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  # MultiLine Example
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
command:
  - sh
  - -c
  - |
    #!/usr/bin/env bash -e
    http () {
        local path="${1}"
        set -- -XGET -s --fail
        # some more stuff here
        curl -k "$@" "http://localhost:5601${path}"
    }
    http "/app/kibana"

